# Generated by Django 3.2.5 on 2021-12-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialtoken',
            name='id_token',
            field=models.TextField(blank=True, help_text='"id_token" OIDC identity token or JWT with scopes', null=True, verbose_name='id token'),
        ),
    ]
